languageCode = "en-US"
baseurl = "http://www.noisy-toys.de/droguedrums/"
title = "droguedrums"
theme = "hugo-alabaster-theme"
metadataformat = "yaml"
pygmentsuseclasses = true 
PygmentsCodeFences = true

[menu]
  [[menu.main]]
    name = "Usage"
    weight = 1
    identifier = "Usage"
    url = "/usage/"

  [[menu.main]]
    name = "Releases"
    weight = 2
    identifier = "Releases"
    url = "/releases/"

[params]
	name = "droguedrums"
	description = "A text file based drum sequencer for the command line"

	github_user   = "sstark"
	github_repo   = "droguedrums"
	github_banner = false

	custom_css = ["css/override.css"]
	custom_js  = []

	#highlightjs = "css/highlight.css"
	highlightjs = ""
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"


	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = false

[params.footer]
	copyright = "[sstark](https://github.com/sstark/)"
	show_powered_by = false
